### ISSUE TITLE
Filename in Export CSV link

### ISSUE THREAD

**Issue by tobias-forkel** [webshopapps/module-matrixrate#10]
We are using common security settings in nginx to block access to sensitive files, such as `zip, tar, gz, csv, sql` etc. Today we had a problem with the button `Export CSV` which is pointing to `matrixrates.csv`.

`
"conditionName/' + $('carriers_matrixrate_condition_name').value + '/matrixrates.csv' )",
`

File: Block/Adminhtml/Form/Field/Export.php

The link was blocked by nginx because of the file extension `csv`. Therefore the export was not working. Instead of lowering our security levels I have decided to remove the filename from the URL because the filename is already hard coded in the controller.

`
public function execute()
{
    $fileName = 'matrixrates.csv';
`

File: Adminhtml/System/ExportMatrixrates.php

I guess you guys are good to remove the filename from the URL.

**Comment by wsagen** [comment]
We've removed the filename from URL in latest version
