### ISSUE TITLE
Postcode mask [Feature request]

### ISSUE THREAD

**Issue by JeffersonTeixeira** [webshopapps/module-matrixrate#101]
Would be nice in ADMIN configuration when the **Use Numeric Zipcode Ranges** = YES an extra option to force removal of non numeric characters from request postcode (getDestPostcode()), in my situation (Brazil) is common the use of mask on it.
An Yes/No would be enough but if you would like to enable regex or an array of characters to remove would be more flexible.

**Comment by PeterElkoShipperHQ** [comment]
Hi,

Thank you for contacting us with this feature request, you can definitely submit a pull request for this. At this time though, we are not adding features to this project. We have transitioned to ShipperHQ, a much more robust system. If you are interested in speaking with someone regarding ShipperHQ please send an email to Sales@ShipperHQ.com.

Have a great day!
Peter
