### ISSUE TITLE
It's not working at magento 2.4.2

### ISSUE THREAD

**Issue by davirs** [webshopapps/module-matrixrate#102]
Hi. The extension don't install by composer at magento 2.4.2(php requirements)
I installed it manually. 

A can set all the extension configuration, but there is no rate at frontend.

![image](https://user-images.githubusercontent.com/4355062/127708458-27e147e9-0a5a-4e20-b10c-f6dca1f3f43a.png)
![image](https://user-images.githubusercontent.com/4355062/127708504-667357d0-1d3f-4817-a6f3-6fa0757a8d2f.png)

**Comment by madonzyaccenture** [comment]
@davirs it wors normally, please check the configuration of "Condition"
<img width="731" alt="Screen Shot 2021-08-03 at 12 56 09" src="https://user-images.githubusercontent.com/72019372/128004259-0b4e77ea-a4b5-4021-a7d0-2dfe9117a584.png">

**Comment by madonzy** [comment]
@davirs it wors normally, please check the configuration of "Condition"
<img width="744" alt="Screen Shot 2021-08-03 at 12 57 21" src="https://user-images.githubusercontent.com/5281020/128004402-250b2aa9-03bb-4b1a-85a7-2fc3072b8298.png">

**Comment by PeterElkoShipperHQ** [comment]
Hi @davirs 

If you do not find a solution with the Condition setting, please send an email to Support@ShipperHQ.com. They can discuss what type of support is available.

Have a great day!
Peter

**Comment by davirs** [comment]
Sorry for the delay. Here at magento 2.4.2-p1 this extension not return any condition of rates.
I did another basic test using example table:

![image](https://user-images.githubusercontent.com/4355062/128527013-208231f0-7d4f-48f5-9a22-801453829211.png)

![image](https://user-images.githubusercontent.com/4355062/128527209-b4817fac-0993-41ec-88c5-9ac1ce6a2621.png)

Returns only the defaut error: "This shipping method is not available. To use this shipping method, please contact us"

**Comment by viniciushenriqueti** [comment]
Same here in Magento 2.4.1.
