### ISSUE TITLE
Composer installation failed on M2.4

### ISSUE THREAD

**Issue by gkopec** [webshopapps/module-matrixrate#104]
I tried to install it via composer but it said:
```
 [Exception]                                                                                                                                    
  Higher matching version 20.2.0 of webshopapps/module-matrixrate was found in public repository packagist.org                                   
                               than 20.1.4 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository
```

**Comment by wsadasmit** [comment]
Hi @gkopec, thanks for raising this. This blocker with composer is related to a recent security update that Adobe released in M2.4.3. Their specific change was:

A new Composer plugin helps prevent dependency confusion and identifies malicious packages with the same names as internal packages on the public package repository. See the [Adobe Releases New Composer Plugin with Magento 2.4.3 Release](https://magento.com/blog/best-practices/adobe-releases-new-composer-plugin-magento-243-release) blog post.

This update unfortunately flags our extension and prevents a composer install, until we can release our newest version in the Adobe Marketplace. This is pending as we speak, but we're just waiting their approval.

In the meantime, Adobe has told us the security module is optional and can be uninstalled. So if you're comfortable doing that, you can run:

composer remove magento/composer-dependency-version-audit-plugin

Then you'll be able to install our module via composer without issue. If you have any other questions, please don't hesitate to reach out!

**Comment by KZNcode** [comment]
Are there any issues with Magento 2.4.3-p1 release?

**Comment by akkhileshviswa** [comment]
> Are there any issues with Magento 2.4.3-p1 release?

Exception #0 (Exception): Notice: Undefined index: id in C:\xampp\htdocs\magento2\vendor\magento\module-config\Model\Config\Structure\Element\Iterator.php on line 63

I am having this error in M2.4.3 while navigating to stores->configuration page to setup the custom table is there any why this error is occurring but system.xml file is same I changed only the the vendor and module name as per my needs 
![error](https://user-images.githubusercontent.com/86413783/144365285-613400e6-be9e-42f4-a1a9-70a3c6b8159b.png)

**Comment by wsadasmit** [comment]
@KZNcode if you are asking if this can occur on that version, yes, this plugin is currently expected to be in all versions of Magento later than 2.4.3.

If you're asking about some other issue, please open a new issue to discuss, or feel free to write to support@shipperhq.com if you have more general questions.

**Comment by Parism** [comment]
Given that Magento introduced the security update to protect from various threats, I think it is not a good idea to remove it as you suggest. 

Is there any other way we can install you module to Magento 2.4.3?

Thank you in advance.

**Comment by wsadasmit** [comment]
Hi @Parism,

In case this might make it more acceptable to you, it should be fine to reinstall the security module after completing the SHQ installation. My understanding is that it just checks version numbers when installing so there shouldn't be any impact on behavior once installed.

Alternatively, if you wait (this can take a few days) and try installing again, it should allow the install with the security module still in place. (This issue occurs for a brief time immediately after a new SHQ module release, and is resolved once that release makes it onto the Magento Marketplace.)

**Comment by jleslie** [comment]
> Hi @Parism,
> 
> In case this might make it more acceptable to you, it should be fine to reinstall the security module after completing the SHQ installation. My understanding is that it just checks version numbers when installing so there shouldn't be any impact on behavior once installed.
> 
> Alternatively, if you wait (this can take a few days) and try installing again, it should allow the install with the security module still in place. (This issue occurs for a brief time immediately after a new SHQ module release, and is resolved once that release makes it onto the Magento Marketplace.)

It's been more than a few days and this is still broken.  Disabling a security module is not an acceptable solution.
