### ISSUE TITLE
Magento 2.4.2-p1 MatrixRate calculates method using order without Tax

### ISSUE THREAD

**Issue by gene-roussetos** [webshopapps/module-matrixrate#105]
Hello,

Not sure if this is a Magento or a module issue, however we have the following.

We have upgraded one of our clients from Magento 2.2.3 to 2.4.2-p1.

The matrixrate with value conditions are including Tax. All the settings for Stores -> Configuration -> Sales -> Tax are set to Include Tax.

We also have a customisation that sorts methods in terms of a priority field (but not affects the conditions in terms of value in any way)

An example rule is, 
for order total < 50 have a Shipping method with a cost
For order total >= 50 have a Shipping method without cost.

All prices include VAT.

While on 2.2.3 this was working as expected, on 2.4.2-p1 this is not working correctly.
We updated the matrixrate to have the from, to condition values to be without Tax to get correct shipping methods (cost for order total < 50 (includes Tax) and free order total > 50 (includes Tax).

However it feels that should not be the case. Can you please advise?

Let me know if you need any more details, thank you!

**Comment by wsajosh** [comment]
Hi @gene-roussetos 

MatrixRate has never supported looking at the tax inclusive cart price I'm afraid. Its getting the package_value from the incoming shipping request from core Magento 2. It sounds like someone might have customised your version of MatrixRate to look at tax inclusive prices and that was lost when you upgraded.
