### ISSUE TITLE
Shipping methods are not shown on checkout page

### ISSUE THREAD

**Issue by anasshl** [webshopapps/module-matrixrate#110]
I installed and setup the module, but I couldn't see the shipping methods on checkout page. After I took a look at logs file I saw this error.

main.DEBUG: Bindings:  {":country_id":"SI",":website_id":1,":condition_name":"package_weight",":condition_value":0} []
main.DEBUG: SQL Select:  ["(website_id = :website_id)","AND (dest_country_id = '0' AND dest_region_id = '0' AND dest_city ='*' AND dest_zip ='*')","AND (condition_name = :condition_name)","AND (condition_from_value < :condition_value)","AND (condition_to_value >= :condition_value)"] 
main.DEBUG: Bindings:  {":website_id":1,":condition_name":"package_weight",":condition_value":0} []

**Comment by gkmbala** [comment]
Yeah, I am facing the same issue on my Magento Instance, 
Now I am using M2.4.3-p1 Version,
Please have a look and update the solution. 
@wsajason : if I anything missing, please let me know. Thnaks.

ERROR:
 main.DEBUG: SQL Select:  ["(website_id = :website_id)","AND (dest_country_id = :country_id AND dest_region_id = :region_id  AND dest_city ='*' AND dest_zip ='*')","AND (condition_name = :condition_name)","AND (condition_from_value < :condition_value)","AND (condition_to_value >= :condition_value)"] []
 main.DEBUG: Bindings:  {":country_id":"GB",":region_id":0,":website_id":1,":condition_name":"package_value",":condition_value":15.83} []

**Comment by ibraheemnabeelfauzi** [comment]
@anasshl  - can you please follow instructions on the following doc to see if this helps rectifies it: https://docs.shipperhq.com/troubleshooting-matrixrates/#No_Shipping_Methods_are_Available
