### ISSUE TITLE
PHP8.1 incompatibility (Magento 2.4.4)

### ISSUE THREAD

**Issue by chris-pook** [webshopapps/module-matrixrate#112]
On checkout I see the following error with Magento 2.4.4 running on PHP8.1

`Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/magento.loc/vendor/webshopapps/module-matrixrate/src/Model/ResourceModel/Carrier/Matrixrate.php on line 207`

**Comment by chris-pook** [comment]
I've added a PR with a temporary solution: https://github.com/webshopapps/module-matrixrate/pull/113

**Comment by HRR1337** [comment]
If someone of webshopapps could merge this, would be perfect!

**Comment by wsajosh** [comment]
Thanks everyone for your contributions. This has been addressed in the latest version of the module. Please update.
