### ISSUE TITLE
Weight and Price Based Filtering

### ISSUE THREAD

**Issue by outrank-james** [webshopapps/module-matrixrate#114]
I know on Mageno 1 this was an option but doesn't seem to be on this on Magento 2

The ability to have multiple filter rules set, i.e. have weight and price based calculations, so the heading would be something like this

Country, Region/State, City, Zip/Postal Code From, Zip/Postal Code To, Weight>, Weight<=, Price>, Price<=, Shipping Price, Shipping Method

This would allow for certain situations where free shipping could be offered on orders over £100, while keeping weight based shipping methods in tact. Also allow for percentage discounts for when an order comes in over £500 for a certain weight.

**Comment by wsajosh** [comment]
Hey @outrank-james, Thanks for getting in touch.

Having multiple filters in play has never been a feature of MatrixRate on Magento 1 or Magento 2. I think that you might be thinking of Premium MatrixRate for Magento 1. This has been replaced by [ShipperHQ](www.ShipperHQ.com) for Magento 2.
