### ISSUE TITLE
Correct shipping method but no price

### ISSUE THREAD

**Issue by adamlavery** [webshopapps/module-matrixrate#115]
Correct shipping method is being detected based on UK postcode but price is coming back as £0. No other shipping methods are enabled.

![image](https://user-images.githubusercontent.com/13659750/187968210-023ebf88-7ca0-430f-a94d-745f22df83bd.png)

**Table entries:**

![image](https://user-images.githubusercontent.com/13659750/187968359-940becc7-e7d6-4f67-89c6-27d6129e75f2.png)

**Debug log:**

`[2022-09-01 16:41:43] main.DEBUG: SQL Results:  [{"pk":"142","website_id":"1","dest_country_id":"GB","dest_region_id":"0","dest_city":"*","dest_zip":"PO31%","dest_zip_to":"","condition_name":"package_weight","condition_from_value":"-1.0000","condition_to_value":"10000000.0000","price":"20.0000","cost":"20.0000","shipping_method":"Isle of Wight"}] []
`

Tried updating to latest release from GitHub - no change. 

Tried modifying "cost" field in the database to match "price" - no change.

Any ideas?

Magento OS 2.4.3-p1

**Comment by adamlavery** [comment]
Issue resolved! Just happened to be testing with one of the few products that get free shipping via cart rules. Added a product that didn't and correct price being returned.

Apologies!

**Comment by wsadaniel** [comment]
Glad you sorted it out and thanks for following up!
