### ISSUE TITLE
Supported PHP versions

### ISSUE THREAD

**Issue by AndrewRMillar** [webshopapps/module-matrixrate#121]
The readme mentions supported PHP versions 7.1.3, 7.2.0 and 7.3.0. And at the same time there is a claimed support for magento version 2.4.4. Those two are mutually exclusive. 

There is no hard PHP requirement in the `composer.json`, so did you just omit changing the readme?

**Comment by WSAlewis** [comment]
Hello @AndrewRMillar, thanks for raising this to us.

I've passed this feedback along to the team to get our compatibility notes updated.
I can confirm that the MatrixRate module is supported up to PHP 8.2.

Let us know if you have any questions or concerns.

Lewis Kennedy - ShipperHQ/WebShopApps Support

**Comment by wsajosh** [comment]
Thanks for raising this @AndrewRMillar, the readme has now been updated
