### ISSUE TITLE
Problems displaying shipping at Magento 2 checkout

### ISSUE THREAD

**Issue by deciobezerra** [webshopapps/module-matrixrate#122]
HI,
We are facing a problem related to shipping calculation, when it is generated on the product page it is displayed correctly, now when the customer needs to complete the purchase, the personalized shipping using the matrix rate is not displayed.

**Comment by WSAlewis** [comment]
Hello @deciobezerra, I can see that you've reached out to our support team via our contact us form and a ticket has been opened.

As this seems to be a configuration based issue, we'll review and reach out to the email address you've provided to our team.

You'll hear from us shortly.

Lewis Kennedy - ShipperHQ/WSA Technical Support

**Comment by deciobezerra** [comment]
Ok, Thanks!
