### ISSUE TITLE
Remove database table after uninstalling.

### ISSUE THREAD

**Issue by bhavyamodi29** [webshopapps/module-matrixrate#123]
### **Preconditions**

Magento Version : 2.4.6-p2
Module Version : 20.4.4

### **Description**

As per standard rule for any module, whenever you disable the module and run the setup:upgrade command, the database tables generated through this file “db_schema.xml” by that module will be deleted. But in this module (“MatrixRate Shipping”), whenever you disable the above module and run the setup:upgrade command, the table named “webshopapps_matrixrate” in the database, which is generated through this file “db_schema.xml” by this module, didn't get deleted.

### **Steps To Reproduce**

  1.  Get the clone of Magento Shop .
       

  2. Install the “ MatrixRate Shipping ” module with the version 20.4.4. After that run the setup:upgrade command.
     
       (e.g. composer require webshopapps/module-matrixrate)  After that   (e.g. php bin/magento setup:upgrade)
     
 
  3. Disable the above module. After that run the setup:upgrade command.
       
       (e.g. php bin/magento module:disable WebShopApps_MatrixRate)  After that   (e.g. php bin/magento setup:upgrade)

  4. After that , open the database and search the table named “webshopapps_matrixrate” and it will appear there. As you can see in 
      the **"Screenshot - 1"**.

### **Screenshot - 1**

![image](https://github.com/webshopapps/module-matrixrate/assets/124759192/d5ca6970-4ada-4753-98e0-c9e4ac2c5445)

### **Expected Result** 

The table should get deleted after disabling the module.

### **Actual Result**

The table did not get deleted after disabling the module.

### **Reason**

As I have checked in this folder “webshopapps/module-matrixrate/src/etc” , there is one file named “db_schema_whitelist.json”  is missing in this folder , as you can see in the **"Screenshot - 2".** So for that reason , whenever you disable the above module , the table named “webshopapps_matrixrate” in the database , which is generated by this module , didn’t get deleted.

### **Screenshot - 2**

![image](https://github.com/webshopapps/module-matrixrate/assets/124759192/4d95dad6-f11d-4177-b6f0-b147e77769a6)

**Comment by WSAlewis** [comment]
Hello @bhavyamodi29, thanks for reaching out to us.

I wanted to let you know that this has been raised with our development team to review further. Either myself or another member of the team will reach out once we have an update on this case.

Let us know if you have any questions or the status of this issue changes.

Lewis Kennedy - ShipperHQ/WebShopApps Support

**Comment by wsajosh** [comment]
@bhavyamodi29 Thanks for raising this and providing a good solution. We've accepted your pull request and your change is in the latest version of the extension
