### ISSUE TITLE
2.4.6

### ISSUE THREAD

**Issue by YiffyToys** [webshopapps/module-matrixrate#125]
You seem to have forgotten to upload the latest release to the Magento store.

![grafik](https://github.com/webshopapps/module-matrixrate/assets/52350973/26061090-555b-438a-8bb1-24f62f3d955b)

**Comment by wsajosh** [comment]
Hey @YiffyToys, thanks. There's been an issue on Adobe Marketplace that's stopping it being uploaded, I'll try again now and update here

**Comment by wsajosh** [comment]
It looks like the issue is resolved, the submission was getting stuck on scanning for malware which was an issue on Adobes side. Once the new version has been approved by Adobe it will be live. They say it could take up to 15 days but in my experience it's usually < 48 hours.
