### ISSUE TITLE
Shipping method not showing

### ISSUE THREAD

**Issue by abi2** [webshopapps/module-matrixrate#13]
I installed this extension using composer,
Enabled and uploaded csv,
When enabling "Show Method if Not Applicable" it shows on website,

Attached is my csv(just changed to .txt)
[CountryExample-2.csv.txt](https://github.com/webshopapps/module-matrixrate/files/637787/CountryExample-2.csv.txt)
And here is my debug log
[debug.log.txt](https://github.com/webshopapps/module-matrixrate/files/637793/debug.log.txt)

Somehow on checkout page its not showing.
Please advise,
Thank You

**Comment by wsajason** [comment]
Hi,

We received an email recently with the same description as the above. If this was not sent by you please re-open the issue here or, if it was, we will follow up by email accordingly.
