### ISSUE TITLE
Shipping by currency

### ISSUE THREAD

**Issue by rguedes** [webshopapps/module-matrixrate#14]
Hi,

My store have 2 currencies (eur and dollar)

Is it possible to set shipping price by currency?

**Comment by wsajosh** [comment]
Hi,

It will use the store currency in the price filter. The price you set in the CSV file should be in the base currency of the website you're uploading the CSV file to. It will be converted by Magento from the base currency to the store currency if they differ.

**Comment by rguedes** [comment]
I need set "manual" price by currency. Not use magento conversion.
