### ISSUE TITLE
Not working with Magento 2.1.3

### ISSUE THREAD

**Issue by abi2** [webshopapps/module-matrixrate#16]
Since I upgraded to Magento 2.1.3 matrix rates are not showing in checkout,
Anyone else having this issue?

**Comment by wsagen** [comment]
Do you have website specific configuration or shipping methods? It seems there was a change in v2.1.3 that has affected website level configuration settings.

**Comment by abi2** [comment]
Matrix is website specific, 
I do not override any settings in website level.

**Comment by wsagen** [comment]
I believe it's related to this issue introduced into Magento 2.1.3 
https://github.com/magento/magento2/issues/7840

We advise you to raise with Magento directly and highlight if this is holding up a go live release or impacting a live site.
