### ISSUE TITLE
no rate returned

### ISSUE THREAD

**Issue by ebaschiera** [webshopapps/module-matrixrate#18]
Hi,
I can't get any rate at checkout, due to what I believe is some incomplete or wrong code: https://github.com/webshopapps/module-matrixrate/blob/master/src/Model/Carrier/Matrixrate.php#L173
Why is the module setting the weight of the package with another value? In my case that $request->getFreeMethodWeight() is always 0, so when searching for a rate in DB, the query results in `...AND (condition_from_value < 0) AND (condition_to_value >= 0)`
If I comment out line 173, I get the correct shipping rate.
I am on Magento EE 2.1.3.

Thank you.

**Comment by permabloom** [comment]
I also had an issue with a price of 0 being returned.

As well as commenting out line 173 I also had to change the below

 if ($request->getFreeShipping() === true || $request->getPackageQty() == $freeQty) {
                    $shippingPrice = 0;
                } else {
                    $shippingPrice = $this->getFinalPriceWithHandlingFee($rate['price']);
                }

removing it and just using the last line of $shippingPrice = $this->getFinalPriceWithHandlingFee($rate['price']);

**Comment by wsagen** [comment]
If the FreeMethodWeight is 0 then you have free shipping enabled on the item or the cart, through some promotional logic. The code in MatrixRate is correct, it only calculates shipping rates on the portion of the cart weight that is not free shipping. 

In both your examples, the freemethodweight is 0 - meaning that the whole cart is shipping free.  

You will see the core Magento Tablerate shipping carrier uses exactly the same logic:
Magento\OfflineShipping\Model\Carrier\Tablerate 
line 143

        // Package weight and qty free shipping
        $oldWeight = $request->getPackageWeight();
        $oldQty = $request->getPackageQty();

        $request->setPackageWeight($request->getFreeMethodWeight());
        $request->setPackageQty($oldQty - $freeQty);

You should review your cart rules and catalog rules to determine why the weight is 0.
