### ISSUE TITLE
Estimate Shipping and Tax does not display the "city" field

### ISSUE THREAD

**Issue by Dart18** [webshopapps/module-matrixrate#19]
I installed the module and it works, but in the cart, the Estimate Shipping and Tax block does not display the city field.
It is a problem because, the shipping charges that I have to apply in matrixrates.csv always show the maximum price shipping for ZIP / postal code entered, and this could discourage the customers.

In addition, but this is a pull request, it would be great a system to automatic fill for the "City", "State/Province", "Country" and "Zip/PostCode" fields, also with manual insertions in the database. The end-user experience would be faster and smarter.

Thanks.

**Comment by wsakaren** [comment]
This is not something we plan to tackle in this free extn as for most people they see this as a restriction. If you need such capabilities our paid offering ShipperHQ supports.
