### ISSUE TITLE
Can't used?

### ISSUE THREAD

**Issue by shuaiZend** [webshopapps/module-matrixrate#2]
Error:
Class WebShopApps\MatrixRate\Model\Config\Source\Matrixrate does not exist
i use php7 and Nginx

**Comment by wsagen** [comment]
Hi, just wondering if you have removed the contents of folders var/generation and var/cache after you installed. I haven't been able to reproduce the error. Perhaps email support@webshopapps.com with the full error log and we can resolve for you.

**Comment by wsagen** [comment]
Closing as no further input from user

**Comment by gopalvenu033** [comment]
Please check the folder names are correct
