### ISSUE TITLE
No Shipping Methods are Available

### ISSUE THREAD

**Issue by nihachi** [webshopapps/module-matrixrate#21]
i tried to install fresh magento. 2.1.1 and 2.1.5 but still not working.

**Comment by pt-p3** [comment]
I have the same problem, on magento enterprise cloud

**Comment by wsagen** [comment]
We definitely support 2.1.x versions. We would need more information to provide support. 

I suggest as a first step you work through the TroubleShooting steps here
http://docs.shipperhq.com/troubleshooting-matrixrates/
If you are still experiencing issues you can email support@webshopapps.com with your CSV file and steps to reproduce.
