### ISSUE TITLE
Migration from Magento 1 to Magento 2

### ISSUE THREAD

**Issue by seagyn** [webshopapps/module-matrixrate#23]
Hi,

We're migrating a Magento store from 1.9.2.2 to Magento 2.1.6. I just need to make sure we're transferring our table rates across. Currently, I am using the Data Transfer Tool provided by Magento but it's still looking for `shipping_matrixrate` and `shipping_premiumrate` documents that are listed on the 1.9.2.2 store but are not mapped with the new version of MatrixRate.

Do you guys have a migration process for the update or am I going to manually have to update everything?

**Comment by wsajosh** [comment]
You'll need to export the tables if you don't have the original CSV files and then import them into Magento through the admin panel. The table structure has changed slightly in MatrixRate - the condition columns have been changed from >= & <= to >= & <.

Premium MatrixRate has been replaced by www.ShipperHQ.com for Magento 2.x.
