### ISSUE TITLE
Condition from _value less than possible should be less than or equal to

### ISSUE THREAD

**Issue by surfer190** [webshopapps/module-matrixrate#24]
If you look at: [The line in the code](https://github.com/webshopapps/module-matrixrate/blob/master/src/Model/ResourceModel/Carrier/Matrixrate.php#L291)

For the case of `package_weight`. If the `:condition_value` parameter is `0`.
Then no results will be returned as the query in SQL will be:

`AND (condition_from_value < 0)`

**Comment by wsajosh** [comment]
You should use * rather than 0. The code caters for that around line 548 of Matrixrate.php

**Comment by surfer190** [comment]
@wsajosh Thanks that worked. In the case of `free shipping` the matrix rates are all changed to free.
Is there a way to ensure matrix rates are not made into free shipping methods.

**Comment by wsajosh** [comment]
That's not something MatrixRate supports. There's support in www.ShipperHQ.com for that.
