### ISSUE TITLE
Carrier with such method not found: matrixrate_xxxxxx, matrixrate

### ISSUE THREAD

**Issue by theflyingfork** [webshopapps/module-matrixrate#26]
Hi there,

Am getting the above error message when using your plugin on checkout after entering a postcode and selecting a shipping method and then  changing the postcode.

This triggers a refresh of the shipping methods whereby the previously selected method is no longer available in the shipping methods matching the revised postcode and so resulting in the above error.

It would seem that the error is triggered by the resolveShippingRates method not being able to find the previously selected shipping method in the refreshed shipping methods collection: https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Checkout/view/frontend/web/js/model/checkout-data-resolver.js#L140

Please advise how to avoid this error.

Thanks,

Dan

**Comment by wsagen** [comment]
Dan,
Can you provide the CSV file you are using and the test address as well as the new postcode you enter in order to reproduce this issue. Also please provide the Magento version you are using. 

If you can email to support@webshopapps.com we will assist

**Comment by theflyingfork** [comment]
Hi Genevieve,

Sorry for the delay. I've done further testing and have figured out that this message does not occur when using the default Magento 2 checkout (although presumably is this exception is occurring in the backend but not output in the UI).

It seems that the issue is related to our use of a 3rd Party One Page Checkout extension http://docs.swissuplabs.com/m2/extensions/firecheckout/ as such I'll raise this issue with them.

Though if you'd still like to investigate on your end let me know and I'll PM you the CSV for testing against M2.1.6

**Comment by wsagen** [comment]
Thanks Dan,

We were seeing expected behaviour locally with own testing so sounds like it is related to the third party checkout. 
Thanks for feeding this back to us. I will close the issue.

Genevieve
