### ISSUE TITLE
Cash on delivery method for specific shipping methods #question

### ISSUE THREAD

**Issue by icbrg** [webshopapps/module-matrixrate#27]
Hello
I would like to know if it's possible to enable Cash on delivery payment method only for specific shipping methods.

For example, if we have 3 shipping methods, if you want to select Cash on delivery, then will show up for example just 1.

**Comment by wsaanthony** [comment]
Hello, So ShipperHQ does not work within the payment method setup areas. You would need to resort to a third party app for this but we can't recommend anything specifically here.
