### ISSUE TITLE
Save address with P.O box : configured shipping method is not showing

### ISSUE THREAD

**Issue by rameshramachandran84** [webshopapps/module-matrixrate#28]
HI Team,

We have noticed an issue related to webshopapps , We configured shipping method for P.O Box .
When customer directly enter P.O address  method will show as confgiured . But when customer selects a pre-saved address which contains P.O box address then configured shipping method will not display . 

Please review and let us know .

Thanks

**Comment by wsajason** [comment]
Matrixrates does not have full support for POBox addresses. Our ShipperHQ solution, however, does fully-support POBoxes as a destination to match on, as illustrated here: http://docs.shipperhq.com/dont-allow-ups-for-shipments-to-po-boxes/
If you would like to discuss the options for moving to ShipperHQ let us know at sales@shipperhq.com

**Comment by rameshramachandran84** [comment]
@wsajason : But POBox addresses is working when csutomer initially add adress and move forward , only issue happens when customer using saved address with P.O box address . Is there any work around for this . We almost reached to Golive and at this moment we may not be able to move forward with shipperHQ.

Please let us know .
