### ISSUE TITLE
can't offer people free shipping as part of a promotion

### ISSUE THREAD

**Issue by dcabrejas** [webshopapps/module-matrixrate#29]
Hi,

I have setup a cart price rule which also gives the users free shipping, but when customers enter the coupon code, there are no shipping rates for them to choose from so they can't actually checkout at all. They are stuck at the checkout shipping step, unable to choose a shipping rate and continue.

How can I go about offering the customer free shipping as part of a promotion so that they can choose free shipping if they have entered a valid coupon with the matrix rate module? 

Thanks.

**Comment by wsajason** [comment]
Matrixrates is not fully-compatible with free shopping cart price rules, I'm afraid. This is fully-supported with our ShipperHQ solution, however, as detailed here: http://docs.shipperhq.com/free-shipping-promotions-in-magento/
If you would like to discuss the options for moving to ShipperHQ let us know at sales@shipperhq.com
