### ISSUE TITLE
Saved address with P.O box : configured shipping method is not showing

### ISSUE THREAD

**Issue by rameshramachandran84** [webshopapps/module-matrixrate#30]
@wsajason :  
Ticket reference : https://github.com/webshopapps/module-matrixrate/issues/28

But POBox addresses is working when customers initially add address and move forward, only issue happens when a customer using saved address with P.O box address. Is there any work around for this. We almost reached to Golive and at this moment we may not be able to move forward with shipper-HQ.

Please let us know .

**Comment by rameshramachandran84** [comment]
Please let us know.
Thanks

**Comment by wsajason** [comment]
There is no support within Matrixrates for filtering based on POBox. If the rates are not being returned based on the address, we will need additional information to diagnose here.
To note, Matrixrates is completely separate from ShipperHQ.
