### ISSUE TITLE
No Shipping Methods

### ISSUE THREAD

**Issue by vseager** [webshopapps/module-matrixrate#34]
Extension installed and rates CSV imported successfully but no methods appearing in checkout.

**Steps to reproduce**
* Install extensions via composer
* Import shipping rates to website via Magento configuration and check database for successful import
* Add product(s) to cart and checkout

**Expected result**
* Shipping method(s) should show

**Actual result**
* "This shipping method is not available. To use this shipping method, please contact us." (as defined in config).

**Additional Information**
* Magento version: 2.1.8
* MatrixRate version: 20.1.2
* Attached screenshots of configuration and checkout
* Tried using "UK Highlands and Islands Postcode filtering" example in MatrixRate KB, and simple rule -
 both exports of shipping rates from configuration attached (changed to .txt format for GitHub).

**Debug Info**
```
[2017-09-18 14:08:11] main.DEBUG: SQL Select:  {"0":"(website_id = :website_id)","1":"AND (dest_country_id = '0' AND dest_region_id = '0' AND dest_city ='*' AND dest_zip ='*')","2":"AND (condition_name = :condition_name)","3":"AND (condition_from_value < :condition_value)","4":"AND (condition_to_value >= :condition_value)","is_exception":false} []
[2017-09-18 14:08:11] main.DEBUG: Bindings:  {":website_id":1,":condition_name":"package_weight",":condition_value":0,"is_exception":false} []
```

[matrixrates_2.txt](https://github.com/webshopapps/module-matrixrate/files/1311194/matrixrates_2.txt)
[matrixrate1.txt](https://github.com/webshopapps/module-matrixrate/files/1311195/matrixrate1.txt)
![checkout](https://user-images.githubusercontent.com/2035088/30550065-4e2ccd44-9c8e-11e7-8193-e5cfde6d420d.png)
![configuration](https://user-images.githubusercontent.com/2035088/30550066-4e2f1f7c-9c8e-11e7-9003-df440515ffa2.png)

**Comment by wsajason** [comment]
Hi,

The CSVs that you attached work successfully with Matrixrates.

You can find common troubleshooting steps here: http://docs.shipperhq.com/troubleshooting-matrixrates/
If your products have a weight of 0, for example, they will not show for a rule for a weight greater than 0.

If you are still experiencing difficulties you can email support@shipperhq.com with your PHP version, extension version and Magento version and we will advise further.

**Comment by minlare** [comment]
Is this related to line 291 of https://github.com/webshopapps/module-matrixrate/blob/master/src/Model/ResourceModel/Carrier/Matrixrate.php

`condition_from_value < :condition_value` should be **less than or equals to** `condition_from_value <= :condition_value`

**Comment by wsajason** [comment]
Hi minlare,

That part of the code is functioning as designed. The conditions columns act as "greater than" followed by "less than or equal to" respectively.

**Comment by minlare** [comment]
Resolved in https://github.com/webshopapps/module-matrixrate/issues/24

**Comment by vseager** [comment]
So it turns out that the problem is because of the above line of code that @minlare has referenced.

We are not using weight on any of our products, so they are 0, and although the `condition_from_value` was set to `0` in the database the cod doesn't allow for this to work. I don't understand the login here, as it would base sense if this was >=, but setting `condition_from_value` to `-1` fixes the issue.

This works fine if you in the import CSV you set the value to `*`. But to add to the confusion, the example shown in the docs at the link below, shows the value as `0`, which for those who don't use the weight attribute is flawed.

http://support.webshopapps.com/matrixrate/postcode-filtering-examples/

**Comment by manishgoswamig** [comment]
> Is this related to line 291 of https://github.com/webshopapps/module-matrixrate/blob/master/src/Model/ResourceModel/Carrier/Matrixrate.php
> 
> `condition_from_value < :condition_value` should be **less than or equals to** `condition_from_value <= :condition_value`
> 
> This seems to break when the condition_from_value is 0 in the table

Thanks @minlare  Shipping methods were not coming because my product weight was **0** . 
Still the code has not been updated  I am using Magento 2.3.5 and I replace  the code 

**$select->where('condition_from_value < :condition_value')** 

with this

 **$select->where('condition_from_value <= :condition_value');**

Now it is working fine for 0 weight product.
