### ISSUE TITLE
Carrier with such method not found when checking out with existing customer

### ISSUE THREAD

**Issue by maderlock** [webshopapps/module-matrixrate#36]
Setup
* Magento 2.1.9
* Matrix rates 20.1.3
* Upload matrix rates with a single shipping method but multiple lines depending on country. See attached [shipping_matrix_example.txt](https://github.com/webshopapps/module-matrixrate/files/1440802/shipping_matrix_example.txt)
* Set default country to same as in file (in this case UAE)

Steps to reproduce
* Create customer with address in default country and specific city (e.g. Dubai in this case)
* Logout
* Add item to basket and visit cart - shipping will be estimated based on default location country, state and zip
* Continue to checkout
* Enter email address of customer and password when prompted
* Press continue button

Expected
* Continue to payment step

Actual
* Error displayed: "Carrier with such method not found: matrixrate_183, matrixrate"

This may sound like an edge case, but for a client that has a lot of existing customers and more than one rule row for a given country, this is going to be a common occurrence (as I have practically found).

What appears to be going on here is that the previously estimated method is submitted with the stored address in the checkout, and Magento 2 attempts to set this. However, by this point the new address has meant that a different rule is active (because with the same name only the cheapest is active), so Magento believes that the shipping method is not available.

To get around this issue I commented out the following lines in /vendor/magento/module-checkout/Model/ShippingInformationManagement.php:

         if (!$shippingAddress->getShippingRateByCode($shippingAddress->getShippingMethod())) {
            throw new NoSuchEntityException(
                __('Carrier with such method not found: %1, %2', $carrierCode, $methodCode)
            );
        }

After doing this I found that could get to the payment step using the same steps. And checkout with some payment methods. However, offline payment methods like Cash on Delivery give the following error when attempting to submit:
"Please specify a shipping method"

So this suggests that the problem has been moved rather than resolved.

**Comment by maderlock** [comment]
I have attempted to recreate a similar issue with built in shipping methods free shipping and flat rate with different countries, but in this case it recalculates after being logged in, so it would appear to be specific to this module.

**Comment by maderlock** [comment]
Unless you believe that this is specifically to do with cities being ignored? I've just spotted https://github.com/magento/magento2/issues/3789

If that's the case, would you recommend trying https://github.com/shopgo-magento2/checkout-city to get around this until they fix the issue?

**Comment by wsagen** [comment]
Hi @maderlock - thanks for raising this.
I am presuming that your shipping rates are dependent on location and are providing a default rate. The rate differs with the address retrieved from login. 

Can you retest this scenario with the built in tablerate carrier. This is more closely related to Matrixrate and would therefore alter the shipping options dependent on address, where as flat rate and free shipping both don't alter shipping rates based on the destination.

**Comment by maderlock** [comment]
They are dependent on location, and I was only getting the issue where the rate depended specifically on city. Built-in rates were fine including table rates, but then that does not support cities. The checkout-blocking problem went away if I used flat rate to do the basic rate for a country and matrix rates to do the city and amount specific rate within the country (though this did of course show two options).

99% sure this is related to magento/magento2#3789 - the problem completely went away by overriding Magento\Quote\Model\ShippingMethodManagement::estimateByAddressId() with http://pastebin.com/3GcesL2H

The issue is supposed to be fixed in 2.1.10, though I have not tested as it only came out today.

**Comment by wsagen** [comment]
It will be related and as such, an issue with core Magento. I am closing this issue.
