### ISSUE TITLE
Removing Magento sampledata fails

### ISSUE THREAD

**Issue by davidbrandastic** [webshopapps/module-matrixrate#37]
When this module is present the command `magento sampledata:remove` fails 

`   [Exception]
  Warning: file_get_contents(<#MAGENTO2PATH#>/vendor/webshopapps/module-matrixrate/src/composer.json): failed to open stream: No such file or directory in <#MAGENTO2PATH#>\vendor\magento\module-sample-data\Model\Dependenc
  y.php on line 109  `

Copying the composer.json from vendor/webshopapps/module-matrixrate/composer.json to vendor/webshopapps/module-matrixrate/src/composer.json and updating:

` "WebShopApps\\MatrixRate\\": "src/" `
 to
` "WebShopApps\\MatrixRate\\": "" `

will allow the removal to process successfully though this is simply a workaround.

**Comment by wsajason** [comment]
Apologies for the delay. We’ve not been able to reproduce this in our test environments so assuming no longer an issue. Please let us know if you need further assistance
