### ISSUE TITLE
Magento 2 - Matrixrates - Sorry, no quotes are available for this order at this time

### ISSUE THREAD

**Issue by Stoppl** [webshopapps/module-matrixrate#38]
**Magento version:** 2.1.9
**Matrixrates:**  20.1.3
**PHP:** 7.0
**MySql:** 5.6.35-1
 
**Issue:**
Since Magento 2.1.3 we have installed the matrixrates module for shipping.
For some times the extension does not work correctly on our magento 2, maybe after the update from magento 2.1.3 to 2.1.9.

When I have one or more articles in my cart an go to check out, I can´t choose a shipping method.

There always appears "Sorry, no quotes are available for this order at this time"

By using the "free shipping" method the shipping method will be shown.

Only Matrixrates seems not to work.

**matrixrates.csv**
The uploaded file you can find attached
[matrixrates.txt](https://github.com/webshopapps/module-matrixrate/files/1478866/matrixrates.txt)

**Explanation**
The logic of the rules should be:
1. WHEN country is Germany AND weight is between 0 AND 399 THAN cost = 0 AND method = DHL Paket

2. WHEN country is Germany AND weight is more than 399 THAN cost = 0 AND method = Spedition

3. WHEN country is everything else AND weight is between 0 AND 399 THAN cost = 0 AND method = DHL Paket International

4. WHEN country is everything else AND weight is more then 399 THAN cost = 0 AND method = Spedition

**Settings**
 
_DEFAULT_
General -> Country Options:
Default Country: system value
Allow Countries: system value
Sales -> Shipping Settings:
Origin
Country: system value
Region: system value
ZIP/Postal Code: system value
Sales -> Shipping Methods:
WebShopApps Matrix Rate
Enable: yes
Condition: Weigt vs. Destination
Ship to Applicable Countries: All Allowed Countries
NOTICE: Only M2E Pro Shipping for eBay is enabled, too.

_Main Websites_
General -> Country Options:
Default Country: Germany
Allow Countries: Only Germany
Sales -> Shipping Settings:
Origin
Country: Germany
Region: Bavaria
ZIP/Postal Code: *****
Sales -> Shipping Methods:
WebShopApps Matrix Rate
Enable: yes
Condition: use default
Ship to Applicable Countries: Specific Countries
Ship to Applicable Countries: Only Germany selected.
NOTICE: Only M2E Pro Shipping for eBay is enabled, too.

_Default Store View_
General -> Country Options:
Default Country: Germany (use Website)
NOTICE: Only M2E Pro Shipping for eBay is enabled, too.

**Comment by wsajosh** [comment]
Hi there,

Can you get the logs please, that will show exactly what is being passed into the extension.

This is how to get logs: http://docs.shipperhq.com/using-the-webshopapps-logger-in-magento-2/

**Comment by Stoppl** [comment]
It seems, that the simple products didn´t have any weight in database.
Thank you for help.
