### ISSUE TITLE
No shipping method found for this quote when we add multiple products

### ISSUE THREAD

**Issue by syedsaleem086** [webshopapps/module-matrixrate#39]
PHP Version 5.6
Magento Version 2.1.1
Magento Version 2.1.5 (same issue)
Operating system: Ubuntu

Matrix rate CSV created based on weight and subtotal. There is no option to select type in backend (per Item or per Order)
Add 2 or more products
-> Add one product which is applicable for free shipping based on its weight and subtotal
-> Add another product which is having some amount based on its weight and subtotal

Once added this product to cart 
**No shipping method found for this quote**

_Hope you are able to reproduce this issue_

[matrixrates.xlsx](https://github.com/webshopapps/module-matrixrate/files/1491406/matrixrates.xlsx)

**Comment by wsajason** [comment]
The extension is designed to use the subtotal weight/price/quantity of the products in the cart, akin to the Table Rates carrier.
From your CSV there are some gaps in the weight ranges, which may be causing this. The weight ranges are "greater than" and "less than or equal to" respectively so a weight of exactly 11 with that CSV would not return rates to (for example) postal code 2264.

**Comment by syedsaleem086** [comment]
Hi @wsajason 

I have tested individual products
For example
Product1 certain postcode of weight 60  **shipping is shown**
Product2 certain postcode of weight 1 **shipping is shown**

combined above products now the sum of weight is 61 and the same postcode used from above
Now issue is 
**shipping method is not available for this quote**

**This condition is working in Magento1** and it fails in **Magento2**

**Comment by wsajason** [comment]
Similarly to above, the combined weight of 61 will not match as the rule is for weight greater than 61. You will need to adjust your weight ranges.
