### ISSUE TITLE
Title replicated in the payment summary

### ISSUE THREAD

**Issue by oviliz** [webshopapps/module-matrixrate#40]
![screenshot from 2017-11-26 21-19-06](https://user-images.githubusercontent.com/73616/33244461-7ad795d0-d2ef-11e7-921e-523329b9f992.png)
Hopefully, the picture speaks more than writing down. Not a big deal but just annoying.

**Comment by wsagen** [comment]
Hi Oviliz

I am presuming that you don't like the format where the summary says "Shipping (Shipping and Handling....)

Unfortunately this output is core Magento functionality. The display is actually "Shipping( Carrier Title - Method Name). I've demonstrated this by altering my own MatrixRates configuration.  We are not able to change the display on the order summary. 
![configuration___settings___stores___magento_admin](https://user-images.githubusercontent.com/4350893/33247503-7f8c7680-d359-11e7-832e-ac63d85ac900.jpg)
![shopping_cart](https://user-images.githubusercontent.com/4350893/33247504-7fc4cc56-d359-11e7-9bf0-afdfffaded00.jpg)


You can alter the carrier title for MatrixRates, or you may be able to use in line translation to alter the "Shipping (" portion of this display.
