### ISSUE TITLE
Multiple rates disappear after selected one

### ISSUE THREAD

**Issue by elachino** [webshopapps/module-matrixrate#43]
We use matrix rates with 4 shipping rates but if i go in checkout select one of this, go back to the cart , when we go in checkout can't find all shipping rates, but we find only selected rates.
I check on magento and i think this is an issue with magento quote that recognize all rates as one shipping method.

**Comment by wsajosh** [comment]
Sorry for the delay in reply to this! It definitely sounds like a Magento issue, I've not experienced this myself and haven't had any other reports to my knowledge about a issue like this. Please let us know if you found the issue.
