### ISSUE TITLE
No shipping methods with migrated customers.

### ISSUE THREAD

**Issue by garrypark** [webshopapps/module-matrixrate#44]
Matrixrates version 20.1.3 
Magento version 2.2.3 

WebShopApps Matrix Rate shipping method not showing with migrated 1.9 customers. 
Magento methods all show.
No problem in Back End using  edit_customer-create order. 
Front End shows correctly until until migrated customer signs in. 
If I create a new customer then everything works fine.
Seems then to be a problem with my Migrated customers from 1.9 (via Data Migration Tool).

Cannot understand whats wrong though.

**Comment by garrypark** [comment]
UPDATE

If I create a new customer then its fine.  
Seems then to be a problem with my Migrated customers from 1.9 (via Data Migration Tool).   
Investigating ....... hopefully not too hard to fix!

**Comment by wsajosh** [comment]
We're not aware of any issues in this area and haven't had any other reports of issues. Please do let us know if the issue is outstanding. I suspect the CSV file didn't upload correctly or the scenario in the checkout isn't catered for in the CSV file.
