### ISSUE TITLE
Regard Weight As KG

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [webshopapps/module-matrixrate#45]
Hello,
       Is possible can i enter weight as KG in webshopapps matrix rate, because Default UPS, FEDEX, DHL required products weight as KG, but i am using Grams for webshopapps matrix rate. Is possible can i use products weight as KG in webshopapps matrix rate.

Thank You.

**Comment by wsajason** [comment]
Hi,
The weight values in Matrixrates are purely numerical. If, for example, you enter a weight of 10 for a product it will use 10 when filtering based on weight in the rules.
