### ISSUE TITLE
New Import CSV Reset Old Data 

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [webshopapps/module-matrixrate#46]
Hello,
I have 2 files, after import first one, then import 2nd file, the first one completely rest by new import. How can  i solve this issue?

**Comment by wsajosh** [comment]
Hi there,

Thanks for getting in touch. 

This is by design. It's working as intended. You need to put all of your rates and rules into one CSV file and upload that. 

Each CSV file that is uploaded will replace the previous one.
