### ISSUE TITLE
Dropdown City

### ISSUE THREAD

**Issue by dzSo** [webshopapps/module-matrixrate#47]
Hello,

Thanks for this extension,

I use it with Magento 2.2.3, but I have a small issue with the city field, I want to make it as a drop-down list to avoid any misspelling, is there any way to do that please?

Thank you

**Comment by wsajosh** [comment]
Hi @dzSo 

There's no way to do that within MatrixRate. It's outside of the scope of the MatrixRate extension I'm afraid.
