### ISSUE TITLE
CSV upload doesnt shown in Database

### ISSUE THREAD

**Issue by Bmacuser1** [webshopapps/module-matrixrate#48]
Hi

i have some strange results to get the matrix extension working in a Multistore setup with 2 websites.

Store 2 import was finally working. But now i cant upload data to the database from store 1. CSV upload is successful but no data shown in the db table. First store is based on the amount the 2nd is based on the weight. In the past i had data from the first store and 2nd store in there. Now with the 2 different files i dont get it running. Any ideas? All csv files are in UTF-8 format.
Cheers
Björn

**Comment by Bmacuser1** [comment]
We have uploaded it manually to the database and know the data from the 2nd store disappeared again even if its in the database and it was working fine before. We have no idea what could cause the issue. Have you tested it in a multistore setup with 2 websites? Just to make shure its working in this setup

**Comment by wsajosh** [comment]
Hi @Bmacuser1 

Thanks for raising this. We're investigating it and will let you know within the next couple of days

**Comment by wsajason** [comment]
Hi,
When testing this in a local environment the CSVs can be uploaded per store when the condition is set differently. Note that in order for the filter to be different you will need to ensure that the "Condition" is changed first, the config is saved then the CSV is uploaded. If the condition is changed at the same time that would cause this discrepancy to occur.
