### ISSUE TITLE
blank page on shipping method

### ISSUE THREAD

**Issue by kytan91** [webshopapps/module-matrixrate#49]
Hi, i am facing blank page on shipping method, i am on magento version 2.2.5 . 
please kindly help. thanks!

**Comment by kytan91** [comment]
![2018-07-15_13-57-06](https://user-images.githubusercontent.com/30074078/42731011-dd5591ec-8836-11e8-9cb9-28c006460372.png)
when disable the module matrixrate module, shipping method work well again. please help . thanks

**Comment by wsajosh** [comment]
Hi @kytan91 Thanks for getting in touch. This usually happens if you're missing a file. I'd recommend that you re-install the module, refresh caches and recompile. If the issue persists please email our support team who can help you out.
