### ISSUE TITLE
How to upload CSV?

### ISSUE THREAD

**Issue by sumihiro** [webshopapps/module-matrixrate#5]
WebShopApps MatrixRate (20.0.3) module was successfully installed with Magento 2.1.0.
But I don't know how to upload my csv.
I referenced http://support.webshopapps.com/matrixrate/csv-management/ , but there are no "Import" menu. This page seems to be old.
I referenced  #4, then I found Stores > Configuration > Shipping Methods > WebShopApps, but I can not found "Choose file" button. See [my screenshot](https://www.dropbox.com/s/casb6y453ja24br/scr%202016-07-28%2019.17.30.png?dl=0).

How to upload CSV?

**Comment by wsagen** [comment]
Hi,

Apologies, we are still in the process of updating our documentation.

You will use the exact same process as outlined in the documentation link above to upload the CSV file. 
1. Navigate to Stores > Configuration > Sales > Shipping Methods. 
2. Open the WebShopApps Matrixrates tab
3. Change your 'Scope' to be Main Website, or the website you wish add shipping rates to.
<img width="1207" alt="configuration___settings___stores___magento_admin" src="https://cloud.githubusercontent.com/assets/4350893/17213615/a325e9ae-5507-11e6-89a4-00333defe28f.png">

4. You will then see a "Browse" button 
<img width="1219" alt="configuration___settings___stores___magento_admin" src="https://cloud.githubusercontent.com/assets/4350893/17213654/d09da246-5507-11e6-9130-e60acd175a45.png">

**Comment by sumihiro** [comment]
I found the button!
Thanks for your advice.
