### ISSUE TITLE
Shipping method not shown

### ISSUE THREAD

**Issue by dmarkos** [webshopapps/module-matrixrate#51]
Hello! 

Thank you for creating this module! It seems that I am having a bit of trouble to make it work though.

I am testing it by giving a few examples in a csv and then using the shop with a few weighted products. This is my csv

> Country | Region/State | City | Zip/Postal Code From | Zip/Postal Code To | Weight> | Weight<= | Shipping Price | Shipping Method |   |  
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> GRC | * | * | * | * | 0 | 5 | 15.0 | “Αποστολή με Courier (μέχρι 5 κιλά) τεστ” |   |  
> GRC | AT | * | * | * | 0 | 5 | 3.0 | “Αποστολή με Courier (μέχρι 5 κιλά)” |   |  

So by adding this product 

![image](https://user-images.githubusercontent.com/5176216/43305876-f5d297ac-9181-11e8-8984-d10871e30262.png)

It should be giving me 15 or 3 as shipping cost, depending on the state I select. However I am not seeing any pricing costs. Instead I get the `missing method` error message.

![image](https://user-images.githubusercontent.com/5176216/43306000-5865236c-9182-11e8-9dbf-1c5a92d1380c.png)

Any ideas?

**Comment by dmarkos** [comment]
I thought to run `setup:di:compile` and i get this error:

> PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/app/code/WebShopApps/MatrixRate/test/Unit/Block/Adminhtml/Form/Field/ExportTest.php on line 37
> 
> Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/app/code/WebShopApps/MatrixRate/test/Unit/Block/Adminhtml/Form/Field/ExportTest.php on line 37

**Comment by dmarkos** [comment]
I installed the module manually. So I uninstalled and used composer. Now I don't have the above `PHP` error. However I still don't see any shipping costs using the above `csv`.

**Comment by wsajosh** [comment]
Hi @dmarkos 

When installing manually you shouldn't copy the test folder over. Please see step 3 here: https://docs.shipperhq.com/installing-the-magento-2-webshopapps-matrixrate-extension/

We've dropped you a email on the other issue you've raised

**Comment by dmarkos** [comment]
Any more info on the debugging?

Στις Παρ, 27 Ιουλ 2018, 4:34 μ.μ. ο χρήστης Josh <notifications@github.com>
έγραψε:

**Comment by wsajosh** [comment]
Hi, yes I've dropped that over in the email for you. You need to enable logging and check the logs

**Comment by dmarkos** [comment]
You mean Magentos logs, or does the all has a debugging mode?

Στις Παρ, 27 Ιουλ 2018, 4:59 μ.μ. ο χρήστης Josh <notifications@github.com>
έγραψε:

**Comment by dmarkos** [comment]
Or does the module has a debugging mode. Thank you for your time btw.

Στις Παρ, 27 Ιουλ 2018, 5:00 μ.μ. ο χρήστης Markos Dimijazz <
dimitsas.markos@gmail.com> έγραψε:

**Comment by dmarkos** [comment]
Hello!

Well, by enabling logging I found out that the weight of the product wasn't registering and it was always considered zero. Besides the fact I had set a product weight. 

i.e. 

> var/log/debug.log

`":condition_name":"package_weight",":condition_value":0`

As it turns out this had to do with my Magento version. I upgraded from 2.2.2 to 2.2.5 and voila, now the module works as expected.

**Comment by wsajosh** [comment]
Hey @dmarkos Thanks for letting us know, glad you figured it out

**Comment by dmarkos** [comment]
No problem! Open source, baby ;)

Στις Δευ, 30 Ιουλ 2018, 11:33 π.μ. ο χρήστης Josh <notifications@github.com>
έγραψε:

**Comment by sajidunnar** [comment]
How we can debug ? its some special option in extension  ?  Extension not generating rates and doesnt make sense why
