### ISSUE TITLE
Enhancement - Images in Shipping Method

### ISSUE THREAD

**Issue by dawhoo** [webshopapps/module-matrixrate#52]
Not sure if this is the proper place or way to ask about enhancement. 

Enhancement request: Allowing the rendering of HTML in the "Shipping Method" field of the .csv

Allowing some HTML would allow for small icons for USPS vs UPS, which people seem to have a really hard time differentiating and/or mouseover tips for the shipping methods, like estimated time, etc..

Again, sorry if this is the wrong area to mention this.

**Comment by wsajosh** [comment]
Hi @dawhoo 

Thanks for the feature request, that would be a great feature! We're currently focused on developing ShipperHQ so we're not taking on any enhancements on MatrixRate I'm afraid, but if you wanted to make the change and create a pull request we'd be happy to merge that in to the main extension
