### ISSUE TITLE
Return $0.00 after selecting more than one products in matrixRate. 

### ISSUE THREAD

**Issue by ajithkumarm107** [webshopapps/module-matrixrate#54]
Return $0.00 after selecting more than one products in matrixRate. The Rules are applied only for one item in the checkout. I double checked the CSV file. it's fine in syntax and configuration. I don't understand the reason for the issue.

**Comment by wsadasmit** [comment]
I recommend turning on the debug levels of logging for the most detailed logs of what is occurring. Please also check that free shipping is not turned on.
As this product is free we are not providing support for this product, but you may find helpful information related to this issue in our documentation for this extension here: http://support.webshopapps.com/matrixrate/
