### ISSUE TITLE
Matrix rate and free shipping in cart rule could be compatible

### ISSUE THREAD

**Issue by mirkocesaro** [webshopapps/module-matrixrate#55]
Hello,
I am using the matrixrate with _package_weight_ as _condition_ and I have a cart rule who apply free shipping when the subtotal is greater than 250. Unfortunately, Matrixrate as it is, does not return any rate because the calculated weight is 0.

```
[2018-09-06 15:06:40] main.DEBUG: SQL Select:  ["(website_id = :website_id)","AND (dest_country_id = '0' AND dest_region_id = '0' AND dest_city ='*' AND dest_zip ='*')","AND (condition_name = :condition_name)","AND (condition_from_value < :condition_value)","AND (condition_to_value >= :condition_value)"] []
[2018-09-06 15:06:40] main.DEBUG: Bindings:  {":website_id":2,":condition_name":"package_weight",":condition_value":0} []
```

I saw inside the magento core, if the free shipping is set, they don't calculate the rowWeight

Inside Magento\Quote\Model\Quote\Address\Total\Shipping::collect
```
...
if ($addressFreeShipping || $item->getFreeShipping() === true) {
    $rowWeight = 0;
} 
...
```

I saw https://github.com/webshopapps/module-matrixrate/issues/29#issuecomment-319010501 and I would like to ask the meaning of this row inside _WebShopApps\MatrixRate\Model\Carrier\Matrixrate::collectRates_ :

`$request->setPackageWeight($request->getFreeMethodWeight());`

I replaced it with:

```
if($conditionName != 'package_weight') {
    $request->setPackageWeight($request->getFreeMethodWeight());
}
```
I added the 'if' only to prevent different behaviour for other conditions and the free shipping is applied correctly. 

Could you help me to understand if the edit is ok, or there is a mistake in it?

Best regards,
Mirko

**Comment by Jeeva-Rathinam** [comment]
@mirkocesaro  Did you solve your isue?

**Comment by wsajosh** [comment]
@mirkocesaro It sounds like a configuration issue in your CSV file. Your weight from rule in the CSV file is most likely starting at 0? If so, replace 0 with an asterisk. That sets it to -1 in the database and will ensure you still get rates with a 0 weight
