### ISSUE TITLE
No shipping methods avaible on manual order backend

### ISSUE THREAD

**Issue by Anesta94** [webshopapps/module-matrixrate#56]
When i try to create a new order from backend i get the error "This shipping method is not available. To use this shipping method, please contact us." How can i solve? Thanks.

**Comment by Anesta94** [comment]
Hi,

All work fine in frontend, the problem is only in backend when I create new order manually.
Is a one store site with two store view ITA/ENG.

Da: wsajason <notifications@github.com>
Inviato: martedì 2 ottobre 2018 18:06
A: webshopapps/module-matrixrate <module-matrixrate@noreply.github.com>
Cc: Antonio Nesta <a.nesta@grafspa.it>; Author <author@noreply.github.com>
Oggetto: Re: [webshopapps/module-matrixrate] No shipping methods avaible on manual order backend (#56)


Hi,

Is this for a single store or multiple stores?
Also, does the same scenario work on the frontend?

**Comment by webamondo** [comment]
I too have this issue, I believe it to be environment related though can't find the issue

**Comment by sajidunnar** [comment]
Having same issue with latest M2 2.2.5 , ...

**Comment by wsajason** [comment]
There are known issue with the store views in the Magento 2 backend (for example, [7840](https://github.com/magento/magento2/issues/7840)). I would recommend updating to the latest version of Magento, which should resolve. In the short term, if you have any country restrictions defined on the store view, disabling the restriction may resolve.
If the module is working correctly on the frontend this would indicate that the extension itself is functional but there is an aspect of the store configuration that is preventing the backend from working correctly.
