### ISSUE TITLE
shipping calc is using greatest cost item subtotal and not Order Subtotal

### ISSUE THREAD

**Issue by todcan67** [webshopapps/module-matrixrate#57]
We have shipping set by zip code ranges and Order Subtotal ranges
Zip/Postal Code From, Zip/Postal Code To,
Order Subtotal>, Order Subtotal

A CSV line looks like this
USA | * | * | 37600 | 37999 | 200 | 299.99 | 50.5 | Zone 8-Overnight shipping

The calculation in the cart works if there is only 1 SKU in the cart or else it pulls only the subtotal from the highest priced SKU in the cart and uses that SKU subtotal to apply the shipping price. The lower priced SKU has no effect on the shipping cost

**Comment by wsajason** [comment]
Hi,
Matrixrates filters by the subtotal of the cart for price filtering, akin to the built-in table rates carrier. If products' prices are being ignored this indicates that there is a third-party aspect that is affecting the shipping calculations. The built-in table rates carrier would provide a similar result in that instance.
This would need to be raised with your developer for further investigation.
