### ISSUE TITLE
Blank page on frontend checkout

### ISSUE THREAD

**Issue by bigbadbaz** [webshopapps/module-matrixrate#59]
I've just installed Matrixrates for the first time on my Magento 2.2.6 dev site. I installed it using composer and followed all instructions on this site and below

https://docs.shipperhq.com/installing-the-magento-2-webshopapps-matrixrate-extension/

The backend is working fine. On the frontend, when I load an item into the cart and click checkout, I am taken to a blank page 

https://acecafe.testpad.com.au/checkout/#shipping

I have tried testing with a very simple one line csv but the result is the same.

I'm not sure if it is relevant but I noticed that composer installs matrixrate into the vendor/webshopapps/module-matrixrate directory and not app/code/WebShopApps/MatrixRate as would be the case with a manual installation.

**Comment by bigbadbaz** [comment]
I have discovered that this issue is unrelated to matrixrate so am closing the issue.

**Comment by wsagen** [comment]
Thanks for coming back and following up with us. Glad to hear it's resolved!
