### ISSUE TITLE
Does not update shipping method automatically

### ISSUE THREAD

**Issue by sumihiro** [webshopapps/module-matrixrate#6]
Hi, 

Shipping method doesn't update automatically in checkout page if user change "Country".

I downloaded and upload CSV which downloaded from your page.
http://support.webshopapps.com/matrixrate/country-based-examples/
Then, when I change "Country" from UK to US:
If there are more than 2 methods, content of shipping method will update automatically.
But, If there are just 1 method (it is your matrix rate module), it doesn't update automatically and I can never change it.

I make screenshots, please reference it.
https://www.dropbox.com/s/d8yeb7ni3qxwxlt/shipping_method_screenshot.png?dl=0

**Comment by wsagen** [comment]
Hi,

The validation may not be loaded on your installation due to caching. Can you 
On your installation, can you please delete the following folders:
* var/di - recompile if you are using compilation
* var/view_processed
* var/cache
* pub/static/frontend
* var/page_cache

Also, please delete your browser cache and retest. 

I'll leave open until I hear from you,

**Comment by sumihiro** [comment]
Hi,

I did them, but nothing improve:
* (var/di  is not found)
* remove var/view_processed
* remove var/cache
* remove pub/static/frontend
* remove var/page_cache
* run /usr/bin/php bin/magento setup:static-content:deploy
* clear cache in Cache Management
* clear browser cache

Can I try any other method?

**Comment by sumihiro** [comment]
I found a rule.
If users change country only, validation will not work.
If users fill zip code and change country, validation will work immediately.

May be, it is specification of Magento. But I am afraid that my customer will be   confused.

**Comment by wsagen** [comment]
Country and post code should trigger an update of rates with the version you have installed. 
I've pushed a new release today that includes some changes to the validation. Rates will now be updated when city, region, post code or country is amended. Can you update please a re-test.

**Comment by sumihiro** [comment]
I installed v20.0.5, but  it seems have a bug.
When I changed country, city or zip, Shipping method never changed.
Your module may be degraded...

**Comment by wsagen** [comment]
There is new version out today that makes further changes here, it appears some countries were failing if they didn't have region drop downs. Apologies for the back and forth. I'm confident this will be resolved. 
 If you are still seeing issues, please can you email us with your site details - we'll have to debug in situ.
