### ISSUE TITLE
Module no longer compiles on Magento 2.2.6

### ISSUE THREAD

**Issue by insanityinside** [webshopapps/module-matrixrate#61]
Can't run bin/magento setup:compile on Magento 2.2.6 - I get a fatal error because of a "'PHPUnit_Framework_TestCase' not found" error.

The exact error was referenced here on the M2 github - https://github.com/magento/magento2/issues/11114 - which suggests replacing PHPUnit_Framework_TestCase with PHPUnit\Framework\TestCase - but while it fixed it on some files, it didn't work on all of them. I'll investigate further, the code seems to work fine when not compiled, but I can't enable code compilation.

**Comment by wsadasmit** [comment]
Hi insanityinside,
It sounds like you have installed from zip and copied the entire outer zip folder contents over instead of the folder within the inner zip, which is called 'app'. This app folder is intended to merge with the existing app folder in the root directory of Magento.

The file structure is as follows:
https://github.com/webshopapps/module-matrixrate/archive/20.1.4.zip
     ┗ZIP folder
          ┗Matrixrates M2-20.1.4.zip
               ┗app folder

**Comment by insanityinside** [comment]
Hi wsadasmit,

Definitely checked it, the app folder was merged with the main app folder, and the code lives in {webroot}/app/code/WebShopApps/MatrixRate . 

The fix was to do a search and replace for PHPUnit_Framework_TestCase -> PHPUnit\Framework\TestCase, and PHPUnit_Framework_MockObject_MockObject -> PHPUnit\Framework\MockObject\MockObject .

I'd offer a patch, but I'm guessing it may break compatibility with older versions - will need proper testing.

**Comment by wsajosh** [comment]
Hi @insanityinside 

If you extract the files from the folder called "ZIP" you'll find that there's no Test directory within there. We've removed it for now from the installable zip.

The directory which the app folder to copy is: module-matrixrate-20.1.4/ZIP

I've triple checked that this is the case, there's definitely no test classes within that directory.

**Comment by insanityinside** [comment]
Sorry, you're right, the newest zip had the test folder removed - when I'd downloaded it from your main website, it came up with the old 20.1.2 zipfile. I'll update to the new one using composer.
