### ISSUE TITLE
search for postcodes within a range are incorrectly

### ISSUE THREAD

**Issue by sonpn** [webshopapps/module-matrixrate#62]
Hi Supporter,
Step to reproduce this bug:
1. import csv shipping rate file with zip code rage
dest_zip dest_zip_to cost
500        90000    123
2. enter zipcode 50000 it shows shipping method correctly
3. enter zipcode 43000 it does not show
I checked and found the problem is the conditional not correctly because it compare INT value (:postcode) with var_char type in the database (dest_zip, dest_zip_to ).

on line 208 in the src/Model/ResourceModel/Carrier/Matrixrate.php
$zipSearchString = ' AND :postcode BETWEEN dest_zip AND dest_zip_to ';

I think we need to use the CAST function to explicitly convert the values to INT

$zipSearchString = ' AND :postcode BETWEEN CAST(dest_zip AS INT) AND CAST(dest_zip_to AS INT)';

Please help us fix this error ASPS thank you

**Comment by wsajosh** [comment]
Hi @sonpn 

Thanks for raising this. We will investigate and release a update if required

**Comment by wsajosh** [comment]
@sonpn Sorry for the delay. I've not been able to replicate this issue. I've done exactly what you've said to do here and I'm getting rates in all scenarios I would expect to
