### ISSUE TITLE
Matrix rate zip code range is not working properly

### ISSUE THREAD

**Issue by singhshubham1** [webshopapps/module-matrixrate#67]
Hi ,
I am using your matrix rate module as i set a csv file 
as in that i have uploaded an csv for example i put 1 line in image ,
![image](https://user-images.githubusercontent.com/43064690/57448190-67853000-7276-11e9-92b1-c8fd4410bba0.png),

Now issue is when i search on cart page 22100 zip code it should show only 1 shipping method  for Spedizione con corriere località disagiata  but it is showing both shipping method as in image :
![image](https://user-images.githubusercontent.com/43064690/57448480-1aee2480-7277-11e9-845d-201e3936183d.png)

Can some 1 help to fix out this?

**Comment by wsajosh** [comment]
Hi. Neither of those rates would appear to be coming from the supplied CSV file. 22100 should not return either of the rates in the supplied file as its outside of the range. You need to double check what's uploaded to your database. The rates are saved to webshopapps_matrixrate

**Comment by singhshubham1** [comment]
Hi Webshopapps/Module-Matrixrate,
This is my database screenshot and attached the csv
[image: image.png]
