### ISSUE TITLE
Shipping Quote given before county and postcode provided on second store

### ISSUE THREAD

**Issue by cannycookie** [webshopapps/module-matrixrate#68]
On the first main store shipping rates are correctly quoted after the user enters a county and postcode.  On the second store when visiting the basket an incorrect rate is shown before the user has entered county or postcode.
See Examples:-

Store 2. No address details entered but rate given
![Screenshot 2019-05-28 at 12 20 52](https://user-images.githubusercontent.com/500822/58474603-912dca80-8143-11e9-90a2-9efc990af593.jpg)

Store 2. Address Details entered, correct rates given
![Screenshot 2019-05-28 at 12 21 12](https://user-images.githubusercontent.com/500822/58474615-9854d880-8143-11e9-9aa2-73873a6a60fb.png)

Store 1. No address details entered - no rates given yet
![Screenshot 2019-05-28 at 12 14 02](https://user-images.githubusercontent.com/500822/58474688-c508f000-8143-11e9-8bc4-c7a2839d47ee.png)

Store 1. Address detailed entered - correct rates given:-
![Screenshot 2019-05-28 at 12 14 22](https://user-images.githubusercontent.com/500822/58474709-d4883900-8143-11e9-878e-464da6f5072c.png)

**Comment by cannycookie** [comment]
Further to this, I have found that the second store on loading the cart page is calling:-
`https://www.buildingsuppliesdirect.com/rest/bsd/V1/guest-carts/pxrLmBzsWHD2WymS6VYMojV58qmL3qXH/estimate-shipping-methods`

But the first store is NOT calling this script.

![Screenshot 2019-05-28 at 12 54 16](https://user-images.githubusercontent.com/500822/58476246-25019580-8148-11e9-8ac7-02338ee2b401.jpg)

![Screenshot 2019-05-28 at 12 54 27](https://user-images.githubusercontent.com/500822/58476300-482c4500-8148-11e9-8b24-f730c9f03f5d.jpg)

I initially suspected a difference between JS merging and minifying between the stores but I have verified merging and minification is disabled on each site.

**Comment by wsajason** [comment]
Hi,

Standard Magento 2 functionality calls to the shipping methods at the cart estimator prior to entering a region/state and/or ZIP/postal code; this is not a feature of Matrixrates.
I would recommend raising this with your store's developer to identify the differences between the stores.
