### ISSUE TITLE
Webshop  Matrix rate Not working in Backend side

### ISSUE THREAD

**Issue by niku0911** [webshopapps/module-matrixrate#69]
I try to Place Order from Backend, but Matrix rate not working they not provide any shipping method.

**Comment by wsajason** [comment]
There are known issue with the store views in the Magento 2 backend for older versions of Magento (for example, [7840](https://github.com/magento/magento2/issues/7840)). I would recommend ensuring that you have the latest version of Magento installed, which should resolve. In the short term, if you have any country restrictions defined on the store view, disabling the restriction may resolve.
If the module is working correctly on the frontend this would indicate that the extension itself is functional but there is an aspect of the store configuration that is preventing the backend from working correctly.
