### ISSUE TITLE
Not able to upload the csv file

### ISSUE THREAD

**Issue by yogendrabmishra** [webshopapps/module-matrixrate#7]
Hello Team,

I have installed the extension and when I choose to export the csv file. I get this error message : 

The file "C:/Users/yogi/AppData/Local/Temp/C:/xampp/tmp/php4ECF.tmp" doesn't exist

Please help how can I fix this issue?

Kind regards,
Yogi

**Comment by wsagen** [comment]
Can you check the permissions on your web server file system as it's likely Magento cannot write to your download or temp directory

**Comment by jameshalsall** [comment]
This happens when `upload_tmp_dir` is set, the module does not handle this properly.

**Comment by jameshalsall** [comment]
PR opened to fix this issue: https://github.com/webshopapps/module-matrixrate/pull/11
