### ISSUE TITLE
Improve query efficiency for large matrixrates tables

### ISSUE THREAD

**Issue by JesKingDev** [webshopapps/module-matrixrate#70]
In instances where the matrixrates table has a high number of records (800k+), the query performance of \WebShopApps\MatrixRate\Model\ResourceModel\Carrier\Matrixrate::getRate can be very poor.

SQL
`SELECT webshopapps_matrixrate.* FROM webshopapps_matrixrate WHERE (website_id = :website_id) AND (dest_country_id = :country_id AND dest_region_id = :region_id AND STRCMP(LOWER(dest_city), LOWER(:city))= ? AND :postcode LIKE dest_zip ) AND (condition_name = :condition_name) AND (condition_from_value < :condition_value) AND (condition_to_value >= :condition_value) ORDER BY dest_country_id DESC, dest_region_id DESC, dest_zip DESC, condition_from_value DESC`

NewRelic Hints:
- The table was retrieved with this index: UNQ_1F88ACC89F513C4E6FE1FEEAD343B921
- MySQL had to do an extra pass to retrieve the rows in sorted order, which is a cause of poor performance but sometimes unavoidable.
- You can speed up this query by querying only fields that are within the index.
-  Or you can create an index that includes every field in your query, including the primary key.
- Approximately 885453 rows of this table were scanned.

Rather than using a wildcard select, it would be more efficient to select only the columns that will be used by the getRate() function.

**Comment by wsajosh** [comment]
@JesKingDev Apologies for the long delay in reply. Thanks for the suggestion. Whilst I can see that there could be improvements that could benefit particularly large tables, this isn't something we're looking to implement ourselves right now. 

If a member of the community implements this, we'd be happy to accept a pull request and put it into the master branch of this repo
