### ISSUE TITLE
Where did 20.2.3 go?

### ISSUE THREAD

**Issue by AndreKlang** [webshopapps/module-matrixrate#71]
We have the version 20.2.3 installed in a few of our stores, but all of a sudden 20.1.5 is the latest.
The tags has disappeared both from github and packagist.

Did someone make a bad force-push, or was there something wrong with 20.2.*?
Also, is there any known issues with 20.1.5 that we will get back if we revert to older version?

**Comment by wsajason** [comment]
Hi,

Version 20.1.5 was incorrectly tagged as 20.2.3 9th May. This was corrected within 7 minutes to the correct tag. Please re-install with the version referenced in your store to reflect ^20.1.5.

**Comment by chris-pook** [comment]
Can I suggest to maybe add this info to README or CHANGELOG? I lost a couple of hours trying to work out how I had a non-existent 20.2.3 installed before finding this closed issue. Thanks.
