### ISSUE TITLE
This shipping method is not available

### ISSUE THREAD

**Issue by jpbazinet** [webshopapps/module-matrixrate#75]
We upgraded from Magento 1 to 2 and installed the version 2 of matrixrate, but are getting the "This shipping method is not available" message.

Here is the CSV (which does import correctly) and a screenshot of DB table

![CSV](https://user-images.githubusercontent.com/55415149/64997324-64e2b900-d8ae-11e9-9a0d-c8285b93c920.png)

![table](https://user-images.githubusercontent.com/55415149/64997367-82178780-d8ae-11e9-8a19-125c592ad545.png)
![Screen Shot 2019-09-16 at 6 30 39 PM](https://user-images.githubusercontent.com/55415149/64997923-2221e080-d8b0-11e9-96d4-d36a0827672b.png)

![Screen Shot 2019-09-16 at 6 31 12 PM](https://user-images.githubusercontent.com/55415149/64997938-37970a80-d8b0-11e9-9751-23bcf1376076.png)

**Comment by jpbazinet** [comment]
Update:

This work's if I'm logged in as a user, but shows no shipping method available if I am a guest.

**Comment by jpbazinet** [comment]
Update:
I had to change condition_from_value from 1.0000 to -1
Any cart's with more than 1 item worked, but a cart with 1 item in it, showed no shipping method available.

**Comment by wsajason** [comment]
Hi,
This is by design - the "rule from" field represents "greater than" and the "rule to" field represents "less than or equal to".
An asterisk (*) in the "rule from" represents no lower limit (-1 in the database) and an asterisk in the "rule to" field represents no upper limit.
