### ISSUE TITLE
Still free shipping on subtotal after discount when must be not free

### ISSUE THREAD

**Issue by HelDoRe** [webshopapps/module-matrixrate#76]
I have a rule :
Country,Region/State,City,"Zip/Postal Code From","Zip/Postal Code To","Order Subtotal>","Order Subtotal<=","Shipping Price","Shipping Method"
GBR,*,*,*,,0.0000,49.9900,4.9500,"Standard delivery"

It is working well, but if the user gets any discount from a coupon or any other discount then it is not working properly as subtotal is not considering discount amount.

If user purchases £50 products then he/she will get the free shipping in the checkout page. But when he uses the coupon that gives £10 discount then the amount will be £40 then also the free shipping is applying.
In stores->settings->configuration->sales->shipping option
flat rate is off
free shippin is off
table rates is off
magebto shipping is off
only WebShopApps Matrix Rate is enabled
magento version 2.2.5
Is there any solutin for this ?
Regards

**Comment by ibraheemnabeelfauzi** [comment]
Hi,

The functionality you're looking for is not supported on the free Matrix Rates extension. It's supported on the higher up paid extension the Premium Matrix Rates: https://webshopapps.com/uk/featured-uk/premium-matrixrate-shipping-extension.html
