### ISSUE TITLE
No shipping methods when there are more than 1 product or quantity in cart

### ISSUE THREAD

**Issue by daviddela12** [webshopapps/module-matrixrate#77]
I don't know if it's really a issue or a configuration problem. I ask by here:

If I add 1 product and 1 quantity of this product to cart and continue on checkout, shipping methods appear correctly.

However, if I increase both the quantity or a new product to cart, shipping methods dissapear...

I don't know why, and what is happening... Anyone else had the same problem as me?

I hope your answer. Thanks

By the way, I'm on Magento 2.3.1

**Comment by avoelkl** [comment]
Interesting, I can see the same behaviour since a few days.
I am currently debugging it, trying to find out more.

Magento 2.3.2

**Comment by avoelkl** [comment]
It seems it had to do with our new import: We had to update (renew) the shipping rates.
I truncated the whole webshopapps_matrixrate table in the database.

However, compared to the old database dump the condition_from_value for our condition "package_weight" was -1.0000 and in the new import we had 0.0001.

In the Matrixrate.php ResourceModel we did not get a match in the where clause condition_from_value < :condition_value as 0.0001 is not lower than 0. This is how I found out about our troubles. I updated the values with -1 as before and it works now. Hope you have a similar problem and it's easy to solve @daviddela12

**Comment by daviddela12** [comment]
Thanks so much, It doesn't seem to be my case. I checked the package_weight in  the both cases:
1 product: package_weight is correct
{:condition_name":"package_weight",":condition_value":2}
2 or more products: package_weight=0
{:condition_name":"package_weight",":condition_value":0}

It can't get the total weight of more than 1 product. I'm still debugging it...If someone know something...it will be welcome.

**Comment by daviddela12** [comment]
I checked 

> Model/Carrieer/Matrixrate.php

> function collectRates

 and the weight value is correct all the time.

However, I see the problem here (line 171):

```
**$request->setPackageWeight($request->getFreeMethodWeight());**
        $request->setPackageQty($oldQty - $freeQty);

        /** @var \Magento\Shipping\Model\Rate\Result $result */
        $result = $this->rateResultFactory->create();
        $zipRange = $this->getConfigData('zip_range');
        $rateArray = $this->getRate($request, $zipRange);

```

Before call getRate set the packageWeight to freeMethodWeight...why? is it normal? I don't understand very well that.

Anyone could help me? or explain if it is correct?

**Comment by wsajason** [comment]
Hi,
Judging by your results the most likely cause there is that a free shipping promo is being applied when the quantity is greater than 1. Due to the limitations of Matrixrates as a free module free shipping promo rules are not supported, I'm afraid.

With regards to your question @daviddela12 that is the weight minus any products' weight that have free shipping.

**Comment by daviddela12** [comment]
Hi, thanks for your answer.
There isn't any free shipping promotions defined.  Futhermore, there isn't any promotion rule defined....

**Comment by daviddela12** [comment]
Anyone found what happens?

**Comment by ibraheemnabeelfauzi** [comment]
Hi @daviddela12 could you please provide us with more insight into why do you think there is an issue with the code specially with QTY's > 1? Provide us with the CSV if as well if possible. 

Cheers.

**Comment by wsajosh** [comment]
Hi. Closing this issue due to lack of response. Please let us know if you're still seeing issues
