### ISSUE TITLE
Magento 2.3 compatibility, update to use latest methodology 

### ISSUE THREAD

**Issue by tr33m4n** [webshopapps/module-matrixrate#78]
Hi there,

I've noticed that this module is relatively out of date with the latest Magento 2.3 methodology, for example your module does not use `db_schema.xml` for adding its new database table. The method you're using is deprecated and should have been updated to use schema patches, which now in turn will be deprecated in favour of `db_schema.xml`.

This creates issues when attempting to extend your module with custom functionality using up to date Magento methodology.

Do you have plans to update your module to use the newer DB architecture?

**Comment by wsajosh** [comment]
Hi @tr33m4n Thanks for raising this. Let me discuss this with our lead engineer here and I'll get back to you by next week

**Comment by wsajosh** [comment]
Hi @tr33m4n 

We're going to review all of our Magento 2 modules and ensure they're in line with the latest Magento 2 methodologies. Thanks for raising this.

We're expecting this to be complete within the next 1-2 months at most. Please look out for new releases of this module.

I'm closing this issue as I've raised a internal issue to action this.
