### ISSUE TITLE
Apply Rates after Discounts

### ISSUE THREAD

**Issue by harrigo** [webshopapps/module-matrixrate#79]
More of a feature request to allow for the rates to be applied after cart price rules as an option. My free shipping can sometimes apply to orders well under the free shipping value under certain conditions as rates applied on subtotal rather than total after the discounts.

Or just wouldn't mind knowing how to quickly botch in I have tried like below in **collectRates** function of **WebShopApps\MatrixRate\Model\Carrier\MatrixRate:**

Changed **$request->getPackageValue()** to **$request->getPackageValueWithDiscount()** for all instances of $request->getPackageValue() however doesn't seem to be working, i just get my error message set in configs showing in order summary in cart page.

       // exclude Virtual products price from Package value if pre-configured
        if (!$this->getConfigFlag('include_virtual_price') && $request->getAllItems()) {
            foreach ($request->getAllItems() as $item) {
                if ($item->getParentItem()) {
                    continue;
                }
                if ($item->getHasChildren() && $item->isShipSeparately()) {
                    foreach ($item->getChildren() as $child) {
                        if ($child->getProduct()->isVirtual()) {
							//changed to $request->getPackageValueWithDiscount() from $request->getPackageValue()
                            $request->setPackageValue($request->getPackageValueWithDiscount() - $child->getBaseRowTotal());
                        }
                    }
                } elseif ($item->getProduct()->isVirtual()) {
					//changed to $request->getPackageValueWithDiscount() from $request->getPackageValue()
                    $request->setPackageValue($request->getPackageValueWithDiscount() - $item->getBaseRowTotal());
                }
            }
        }

        // Free shipping by qty
        $freeQty = 0;
        if ($request->getAllItems()) {
            $freePackageValue = 0;
            foreach ($request->getAllItems() as $item) {
                if ($item->getProduct()->isVirtual() || $item->getParentItem()) {
                    continue;
                }

                if ($item->getHasChildren() && $item->isShipSeparately()) {
                    foreach ($item->getChildren() as $child) {
                        if ($child->getFreeShipping() && !$child->getProduct()->isVirtual()) {
                            $freeShipping = is_numeric($child->getFreeShipping()) ? $child->getFreeShipping() : 0;
                            $freeQty += $item->getQty() * ($child->getQty() - $freeShipping);
                        }
                    }
                } elseif ($item->getFreeShipping()) {
                    $freeShipping = is_numeric($item->getFreeShipping()) ? $item->getFreeShipping() : 0;
                    $freeQty += $item->getQty() - $freeShipping;
                    $freePackageValue += $item->getBaseRowTotal();
                }
            }
			//changed to $request->getPackageValueWithDiscount() from $request->getPackageValue()
            $oldValue = $request->getPackageValueWithDiscount();
            $request->setPackageValue($oldValue - $freePackageValue);
        }

**Comment by wsajosh** [comment]
Hi @harrigo 

Thanks for getting in touch. Unfortunately this isn't a supported feature of MatrixRate and isn't something that we're looking to add support for as its supported in ShipperHQ along with a host of other features such as:
- Different shipping options/prices based on product
- Filter on price, weight & quantity simultaneously
- Enhanced UK, Canadian and numerical postal code support

**Comment by TheFrakes** [comment]
Hi @harrigo,
I was trying to do the same and landed here as well. Did you find a workaround or solution you could send me?
@wsajosh I understand that this will not be implemented in a backend function. But may we ask you just to share an in-code solution to manually override the code in a "quick and dirty" way?

**Comment by jgmdigital** [comment]
Hi @TheFrakes, did you have any luck with this?

**Comment by TheFrakes** [comment]
Unfortuatenly, no.

**Comment by kestraly** [comment]
@TheFrakes  and @jgmdigital - In the above code you could change

```
$oldValue = $request->getPackageValueWithDiscount();
 $request->setPackageValue($oldValue - $freePackageValue)
```

to 

`$request->setPackageValue($PackageValue);`


and then within the foreach add  $PackageValue

```
$freePackageValue = 0;
$PackageValue = 0;
 foreach ($request->getAllItems() as $item) {
            if ($item->getProduct()->isVirtual() || $item->getParentItem()) {
                continue;
            }
            $PackageValue += $item->getBaseRowTotalInclTax() - $item->getBaseDiscountAmount();
...

```


$PackageValue)
