### ISSUE TITLE
Shipping method not displaying - from order create in admin-end. 

### ISSUE THREAD

**Issue by poongud** [webshopapps/module-matrixrate#8]
Hello,

We have installed you module to my website magento 2.1.0.

Front end shipping methods are displaying as my shipping rates configuration.

Then I tried from admin end from create order option in Customer management section.

Kindly fix it.

**Comment by poongud** [comment]
Reason may be !!

Query bind array data invalid  $bind[':condition_value'] = 0 for every request

 $bind[':website_id'] = (int)$request->getWebsiteId();
            $bind[':condition_name'] = $request->getConditionMRName();
            $bind[':condition_value'] = $request->getData($request->getConditionMRName());

**Comment by wsagen** [comment]
Using MatrixRate for orders placed in the admin panel is fully supported. 

Can you please review your MatrixRate configuration and ensure you have enabled and saved the configuration for the default scope and the store you are placing the admin order in. 

If you are still experiencing issues, can you email with details of the issue and any logs from debug.log to support@webshopapps.com and we'll assist.
