### ISSUE TITLE
Carrier with such method not found

### ISSUE THREAD

**Issue by Rudraksham** [webshopapps/module-matrixrate#80]
Getting this error message on checkout page after upgrading Magento from 2.3 to 2.4

"carrier with such method not found: matrixrate_2029, matrixrate"

**Comment by live4soccer7** [comment]
Is this module compatible with magento 2.4 and php 7.4?

**Comment by wsajosh** [comment]
Hi. This module is compatible with Magento 2.4 and PHP 7.4. The original issue sounds like a caching issue and would have resolved itself once the cache expired or was refreshed.
