### ISSUE TITLE
Carrier with such method not found: %1, %2", parameters: ["matrixrate", "matrixrate_1539

### ISSUE THREAD

**Issue by sachinvelocitai** [webshopapps/module-matrixrate#86]
Hello Team,

I am getting this error when I click on next on checkout page in the console it shows me the error

Carrier with such method not found: %1, %2", parameters: ["matrixrate", "matrixrate_1539

And when I click second time it works properly and moves to the payment page.

On single click its showing me an error but on second click its is working how ?

Address data is going through properly nothing is missing.

{"addressInformation":{"shipping_address":{"countryId":"GB","region":"","street":["22 cosgrove way"],"telephone":"123256478","postcode":"JE12 3CD","city":"London","firstname":"Sachi ARora"},"billing_address":{"countryId":"GB","region":"","street":["22 cosgrove way"],"telephone":"123256478","postcode":"JE12 3CD","city":"London","firstname":"Sachi ARora","saveInAddressBook":null},"shipping_method_code":"matrixrate_1539","shipping_carrier_code":"matrixrate","extension_attributes":{}}}

Please help and reply

**Comment by wsajason** [comment]
Hi @sachinvelocitai Can you confirm the version of Magento 2 you are using and whether you are using a third-party checkout?
I would also recommend re-uploading the CSV to ensure Magento's method codes are refreshed.

**Comment by sachinvelocitai** [comment]
Hello @wsajason ,

Thanks for the quick reply, no i am not using any third-party extension for checkout and Magento version 2.3.1. And I am attaching the csv [matrixrates (8).zip](https://github.com/webshopapps/module-matrixrate/files/4836727/matrixrates.8.zip)
please check once.

Please help and reply
