### ISSUE TITLE
Magento 2.3 - Shipping Matrix Rate calculation partially working

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [webshopapps/module-matrixrate#89]
I am using webshop shipping matrix rate, if cart value below 50 then only showing shipping methods, above 50 not shown, how to solve this error?

**Comment by wsajason** [comment]
Hi @Jeeva-Rathinam 
You'll need to ensure that the cart contents is able to match on the rules in the CSV. This article explains in greater detail, together with additional troubleshooting tips: https://docs.shipperhq.com/troubleshooting-matrixrates/#No_Shipping_Methods_are_Available

**Comment by Jeeva-Rathinam** [comment]
@wsajason Here is my database: https://snipboard.io/linb4Y.jpg I hope my column's values are right?

**Comment by Jeeva-Rathinam** [comment]
> Hi @Jeeva-Rathinam
> You'll need to ensure that the cart contents is able to match on the rules in the CSV. This article explains in greater detail, together with additional troubleshooting tips: https://docs.shipperhq.com/troubleshooting-matrixrates/#No_Shipping_Methods_are_Available

Anything error in my DB?

**Comment by adityanvd** [comment]
Hello @Jeeva-Rathinam 

Did you find any solution for this, we are facing the same issue !. The same sheet was working fine in magento 1 , but now in magento 2 it is not showing weights for more than 500 grams.

**Comment by xgiovio** [comment]
Weight are in kg

**Comment by adityanvd** [comment]
Yes, we have put it as per kg. It is working for weights :  0.5 and the shipping rates are coming correct till this weight, but beyond this rates are not coming/

**Comment by xgiovio** [comment]
Strange. We are using it and it works with no problem on 2.4.2
