### ISSUE TITLE
Method names not shown in getAllowedMethods()

### ISSUE THREAD

**Issue by Frits1980** [webshopapps/module-matrixrate#9]
In my custom module I want to do something with the shippingmethods. But I can't get the methods. I get the core module methods like UPS and DHL and so on. But only the carrier from Matrixrates is visible.

Also in Marketing>Cart price rules> condition > shipping method it's not possible to get a shipping method from MatrixRate.

**Comment by wsagen** [comment]
Thanks for raising - this is a feature request rather than an issue. We don't support individual shipping method filtering on rules with MatrixRates.
