### ISSUE TITLE
Showing same method twice on the checkout page.

### ISSUE THREAD

**Issue by manishgoswamig** [webshopapps/module-matrixrate#91]
I have installed the extension and configured it.

When I use **country and zip code** it is showing the same method twice.I used the zip code **50016** 

![webshop_git](https://user-images.githubusercontent.com/46725562/90355937-7e1a5980-e06b-11ea-9cb0-07021f368b6b.png)

In the dabase the query is :- 

![image](https://user-images.githubusercontent.com/46725562/90355867-47dcda00-e06b-11ea-9f71-96ec819e188f.png)

**Comment by manishgoswamig** [comment]
I have got the solution we need to zipcode **type cast as integer**  .

File path :- WebShopApps/MatrixRate/Model/ResourceModel/Carrier/Matrixrate.php

/* Please replace this code with older one.  */
![image](https://user-images.githubusercontent.com/46725562/90356217-5a0b4800-e06c-11ea-8f7e-4be97c041f7e.png)

**Comment by wsajason** [comment]
Hi @manishgoswamig I have tested this same scenario with the latest version of the module with rules based on the rules from your database table screenshot and can confirm that the rules only match on the 39000-50999 range. Please ensure that you have set "Use Numeric Zipcode Ranges" to "Yes" via Stores > Configuration > Sales > Shipping Methods > Matrixrates and that no other rules within the CSV overlap.
