### ISSUE TITLE
Magento 2.4.x compatible and php 7.4?

### ISSUE THREAD

**Issue by live4soccer7** [webshopapps/module-matrixrate#92]
Is it compatible with the M2.4.x and php 7.4?

**Comment by wsajason** [comment]
Hi @live4soccer7 
There are no known incompatibilities with Magento 2.4 or PHP 7.4, as long as the [PHP version is supported by Magento](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html). Currently PHP 7.4.2 is not recommended by Magento.

**Comment by live4soccer7** [comment]
Thank you very much!
