### ISSUE TITLE
Base table or view not found: 1146 Table 'u706765422_711cU.lkik_webshopapps_matrixrate' doesn't exist

### ISSUE THREAD

**Issue by BoutiqueBedCompany** [webshopapps/module-matrixrate#96]
I see other people have had this issue and it hasn't been solved.
I am using Magento version 2.3.5-p2.
I followed the installation notes to the T. 
The installation was successful and the extension is visible on the backend.

My problem is, when I try to export or import a table, I get this error message about the SQL base table.
I have included a screenshot.

Is there a way I can manually upload the base table to MySWL?
What's gone wrong?

![Screenshot (60)](https://user-images.githubusercontent.com/74540374/99432110-9b2d2580-2903-11eb-91fd-60a584f5a3e5.png)

**Comment by ibraheemnabeelfauzi** [comment]
Hi @BoutiqueBedCompany  
Please follow the instructions on this doc to resolve this: https://docs.shipperhq.com/resolve-failed-sql-run-magento/#Magento_2 

Thank you.

**Comment by BoutiqueBedCompany** [comment]
Salaam, Thank you for your quick reply Ibrahee,.
Unfortunately this article wasn't useful.
There must be some kind of typo in the coding somewhere?

**Comment by BoutiqueBedCompany** [comment]
UPDATE

I found a typo in the Setup/InstallSchema.php file... Should be country.

After this, I build the SWL Database named "lkik_webshopapps_matrixrate.sql" from scratch using the InstallSchema.php as a reference point.

It is now working.

![Screenshot (61)](https://user-images.githubusercontent.com/74540374/99536848-cf0b5800-29a2-11eb-9d2b-02db4adbd07d.png)
