### ISSUE TITLE
This shipping method is not available

### ISSUE THREAD

**Issue by edsonjunior2021** [webshopapps/module-matrixrate#99]
**Version**
Magento 2.4.1

Always this error

![Captura de tela de 2021-05-13 09-35-28](https://user-images.githubusercontent.com/72230468/118126366-9c30a280-b3ce-11eb-8a38-e9f0cf37d94b.png)

Even if I select and try to advance, it returns me **matrixrate, null**

In **Model/Carrier/Matrixrate.php** method **collectRates** in **$rateArray = $this->getRate($request, $zipRange)** return empty.
Why in ResourceModel/Carrier/Matrixrate.php **getRate** line 307 **$adapter->fetchAll** return empty

**Comment by ibraheemnabeelfauzi** [comment]
Hi, @edsonjunior2021  

Please email us on support@shipperhq.com and we'll provide further information.

**Comment by edsonjunior2021** [comment]
> Hi, @edsonjunior2021
> 
> Please email us on [support@shipperhq.com](mailto:support@shipperhq.com) and we'll provide further information.

Have to send an email? I thought that the doubts of problems would take away here, sorry. However, thank you very much, I will try to resolve it here.

**Comment by ibraheemnabeelfauzi** [comment]
@edsonjunior2021  
Apologise here but the reason I asked for this to be communicated via email is so that I can have you send me the matrixRate CSV as the above is likely caused by a postal code or a product that didn't match on it and for that reason, it didn't fetch rates. Thanks!

**Comment by edsonjunior2021** [comment]
> @edsonjunior2021
> Apologise here but the reason I asked for this to be communicated via email is so that I can have you send me the matrixRate CSV as the above is likely caused by a postal code or a product that didn't match on it and for that reason, it didn't fetch rates. Thanks!

**OK no problem.**

in **ResourceModel/Carrier/Matrixrate.php** switch always to nº 7

**that way it doesn't work**

`$zoneWhere =  "dest_country_id = '0' AND dest_region_id = '0' AND dest_city ='*' AND dest_zip ='*'";`

**if I change this code in this way, it works.**

`$zoneWhere =  "dest_country_id = '0' AND dest_region_id = '0' AND dest_city ='*' " . $zipSearchString;`

However I want to understand why it is not working, I am trying to see it.
